# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b39d4d2160e0f2dc8867f3b0d302e2467be8af3f017410ce69ac2322364b3afbae0793859eef5cf4b0f811665f2dfa743cbeacce6d573d3f66fcc5cce9b8af4b

test:
  secret_key_base: be89ec5876e00c9b2e87fb999d03728bf4e6deb5239e79ce44983e540273700e790b677ce05c87c8ac6582e8454c800bc6ec9315036af724e2a4e3b04bd438a8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
